theme: jekyll-theme-slate
title: Starting from scratch in Maker movement 
description: Welcome to the repository, here you can find my experiences in Pop Machina Academy in order to learn, almost everything, about the Maker movement
